pipeline{
  agent any
  stages{
    stage(‘Build’){
      steps{
        sh ‘docker build –t .’
        sh ‘docker push’
      }
   }
   stage(‘Build’){
      steps{
        sh ‘docker pull’
        sh ‘docker run -t ‘
      }
    }
  }
}

