pipeline{
  agent any
  stages{
    stage('Test & Build'){
      steps{
        sh 'docker build -f project/Dockerfile -t thehaohcm/jenkinslab:latest ./project/'
        sh 'docker image push thehaohcm/jenkinslab:latest'
      }
   }
   stage('Deploy'){
      steps{
        sh 'docker image pull thehaohcm/jenkinslab:latest'
        sh '''
          if [ "$( docker container inspect -f '{{.State.Running}}' docker-gs-ping )" = "true" ]; then
            docker stop docker-gs-ping
          fi
           '''
        sh 'docker run -d --rm --name docker-gs-ping -p 8081:8080 thehaohcm/jenkinslab:latest'
      }
    }
  }
}